# Generated by Django 4.2.1 on 2023-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Women'), ('U', 'Unisex')], default='M', max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/}', verbose_name='Image'),
        ),
    ]
