# Generated by Django 4.2.1 on 2023-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetail',
        ),
    ]
