# Generated by Django 4.2.1 on 2023-05-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchoffice',
            name='image',
            field=models.ImageField(null=True, upload_to='images/slider/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subtitle',
            field=models.CharField(default='', max_length=50, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(default='', max_length=50, verbose_name='Subtitle'),
        ),
    ]
