# Generated by Django 4.2.1 on 2023-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_branchoffice_image_alter_collection_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sale',
            field=models.CharField(default='', max_length=10, verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Subtitle'),
        ),
    ]
